### ISSUE TITLE
HW 1 Errors

### ISSUE THREAD

**Issue by NicholasAsirvadam** [ElisaJean0299/IDS2024S#2]
Hello, the following are errors I have found in your first homework assignment:
1. The link you have included to the course webpage does not work.

Since this is the first assignment, you have the opportunity to earn some points back on these mistakes if you resolve these issues by the start of class on Monday.

**Comment by ElisaJean0299** [comment]
I fixed the issue, you are now able to see the the course webpage. Apologies for not replying sooner, my own page took a while for it to update in order to see the course webpage. Again it successfully works!
